package panel;

import controlador.AlbumDAO;
import java.util.Comparator;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelos.Album;
import modelos.Artista;
import servicio.Servicio;

public class AlbumPanel extends javax.swing.JPanel {

    AlbumDAO albumDAO = new AlbumDAO();
    DefaultTableModel model;

    /**
     * Creates new form AlbumPanel
     */
    public AlbumPanel() {
        initComponents();
        mostrarDatosEnTabla(tblAlbums);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void mostrarDatosEnTabla(JTable tabla) {
        Object[] datos = new Object[10];
        Album.albums.sort(Comparator.comparing(Album::getId));

        model = (DefaultTableModel) tabla.getModel();
        Album.albums.stream().forEach(a -> {
            Artista artista = Servicio.buscarArtistaPorId(a.getArtistaId());

            if (artista != null) {
                datos[0] = a.getId();
                datos[1] = a.getNombre();
                datos[2] = a.getAnio();
                datos[3] = artista.getNombre();
            } else {
                datos[0] = a.getId();
                datos[1] = a.getNombre();
                datos[2] = a.getAnio();
            }

            model.addRow(datos);
        });
        tabla.setModel(model);
    }

    public void limpiarDatos() {
        txtIdAlbum.setText("0");
        txtNombreAlbum.setText("");
        txtAnioAlbum.setText("");
        txtIDAlbumArtista.setText("0");
        txtNombreAlbumArtista.setText("");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRespuesta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlbums = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDAlbumArtista = new javax.swing.JTextField();
        txtNombreAlbumArtista = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rbRespuestaArtistaSi = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtNombreAlbum = new javax.swing.JTextField();
        txtAnioAlbum = new javax.swing.JTextField();
        rbRespuestaArtistaNo = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtIdAlbum = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(34, 45, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/album.png"))); // NOI18N

        tblAlbums.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblAlbums.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblAlbums.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Anio", "Artista"
            }
        ));
        tblAlbums.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblAlbums.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblAlbums.getTableHeader().setReorderingAllowed(false);
        tblAlbums.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlbumsMouseClicked(evt);
            }
        });
        tblAlbums.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblAlbumsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlbums);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Anio");

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nombre");

        txtIDAlbumArtista.setEditable(false);
        txtIDAlbumArtista.setBackground(new java.awt.Color(204, 204, 204));
        txtIDAlbumArtista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtIDAlbumArtista.setText("0");

        txtNombreAlbumArtista.setEditable(false);
        txtNombreAlbumArtista.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreAlbumArtista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(3, 124, 215));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-32.png"))); // NOI18N
        btnBuscar.setText("Buscar Artista");
        btnBuscar.setEnabled(false);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(3, 124, 215));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Filtrar");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreAlbumArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(txtIDAlbumArtista)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIDAlbumArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreAlbumArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Desea Agregarle un artista?");

        btnRespuesta.add(rbRespuestaArtistaSi);
        rbRespuestaArtistaSi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbRespuestaArtistaSi.setForeground(new java.awt.Color(255, 255, 255));
        rbRespuestaArtistaSi.setText("Si");
        rbRespuestaArtistaSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRespuestaArtistaSiMouseClicked(evt);
            }
        });
        rbRespuestaArtistaSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRespuestaArtistaSiActionPerformed(evt);
            }
        });

        txtNombreAlbum.setBackground(new java.awt.Color(34, 45, 65));
        txtNombreAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombreAlbum.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreAlbum.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtAnioAlbum.setBackground(new java.awt.Color(34, 45, 65));
        txtAnioAlbum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAnioAlbum.setForeground(new java.awt.Color(255, 255, 255));
        txtAnioAlbum.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtAnioAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioAlbumActionPerformed(evt);
            }
        });

        btnRespuesta.add(rbRespuestaArtistaNo);
        rbRespuestaArtistaNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbRespuestaArtistaNo.setForeground(new java.awt.Color(255, 255, 255));
        rbRespuestaArtistaNo.setText("No");
        rbRespuestaArtistaNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRespuestaArtistaNoMouseClicked(evt);
            }
        });
        rbRespuestaArtistaNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRespuestaArtistaNoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(3, 124, 215));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");

        txtIdAlbum.setBackground(new java.awt.Color(34, 45, 65));
        txtIdAlbum.setForeground(new java.awt.Color(255, 255, 255));
        txtIdAlbum.setText("0");

        jButton3.setBackground(new java.awt.Color(27, 187, 125));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(252, 211, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        jButton5.setText("Actualizar");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator3)
                                                    .addComponent(jSeparator4)
                                                    .addComponent(txtAnioAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(140, 140, 140)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbRespuestaArtistaSi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rbRespuestaArtistaNo))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtIdAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnioAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rbRespuestaArtistaSi)
                            .addComponent(rbRespuestaArtistaNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbRespuestaArtistaSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRespuestaArtistaSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRespuestaArtistaSiActionPerformed

    private void txtAnioAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioAlbumActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbRespuestaArtistaSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRespuestaArtistaSiMouseClicked
        // TODO add your handling code here:
        btnBuscar.setEnabled(true);
    }//GEN-LAST:event_rbRespuestaArtistaSiMouseClicked

    private void rbRespuestaArtistaNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRespuestaArtistaNoMouseClicked
        // TODO add your handling code here:
        if (rbRespuestaArtistaNo.isSelected()) {
            btnBuscar.setEnabled(false);
            txtIDAlbumArtista.setText("0");
            txtNombreAlbumArtista.setText("");
            Servicio.id = null;
            Servicio.nombre = null;
        }

    }//GEN-LAST:event_rbRespuestaArtistaNoMouseClicked

    private void rbRespuestaArtistaNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRespuestaArtistaNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRespuestaArtistaNoActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        if (rbRespuestaArtistaSi.isSelected()) {
            TablaAlbumBuscador tabla = new TablaAlbumBuscador();
            tabla.setVisible(true);
        }

    }//GEN-LAST:event_btnBuscarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        Date creadoEl = new Date();
        Album nuevoAlbum = new Album();
        String nombreAlbum = txtNombreAlbum.getText();
        int anio = Integer.parseInt(txtAnioAlbum.getText());
        int id = Integer.parseInt(txtIDAlbumArtista.getText());

        int idAlbum = Integer.parseInt(txtIdAlbum.getText());

        Album AlbumEncontrado = Servicio.buscarAlbumPorId(idAlbum);

        if (AlbumEncontrado == null) {
            nuevoAlbum.setNombre(nombreAlbum);
            nuevoAlbum.setAnio(anio);
            nuevoAlbum.setArtistaId(id);
            nuevoAlbum.setCreadoEl(creadoEl);
            albumDAO.guardarAlbum(nuevoAlbum);
            Album.albums.clear();
            albumDAO.obtenerAlbum();
            Servicio.limpiarTabla(tblAlbums);
            mostrarDatosEnTabla(tblAlbums);
            JOptionPane.showMessageDialog(null, "Registro Guardado!");
            limpiarDatos();
        } else {
            JOptionPane.showMessageDialog(null, "Registre ya Existe!");
            limpiarDatos();
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        txtIDAlbumArtista.setText(Servicio.id);
        txtNombreAlbumArtista.setText(Servicio.nombre);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblAlbumsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAlbumsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAlbumsKeyPressed

    private void tblAlbumsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlbumsMouseClicked
        // TODO add your handling code here:

        int fila = tblAlbums.getSelectedRow();
        if (fila == -1) {
            System.out.println("seleccione una fila");

        } else {

            txtIdAlbum.setText((String) tblAlbums.getValueAt(fila, 0).toString());
            txtNombreAlbum.setText((String) tblAlbums.getValueAt(fila, 1).toString());
            txtAnioAlbum.setText((String) tblAlbums.getValueAt(fila, 2).toString());
            int id = Integer.parseInt(tblAlbums.getValueAt(fila, 0).toString());
            Album albumEncontrado = Album.albums.stream().filter(album -> album.getId() == id)
                    .findFirst()
                    .orElse(null);
            Artista artista = Servicio.buscarArtistaPorId(albumEncontrado.getArtistaId());
            if (artista == null) {
                txtIDAlbumArtista.setText("0");
                txtNombreAlbumArtista.setText("");
            } else {
                String idArtista = String.valueOf(artista.getId());
                String nombrArtista = String.valueOf(artista.getNombre());
                txtIDAlbumArtista.setText(idArtista);
                txtNombreAlbumArtista.setText(nombrArtista);
            }
        }
    }//GEN-LAST:event_tblAlbumsMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        limpiarDatos();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdAlbum.getText());
        albumDAO.eleminarAlbum(id);
        JOptionPane.showMessageDialog(null, "Registro eliminado!");
        Album.albums.clear();
        albumDAO.obtenerAlbum();
        Servicio.limpiarTabla(tblAlbums);
        mostrarDatosEnTabla(tblAlbums);
        limpiarDatos();


    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        Date actualizadoEL = new Date();
        Album nuevoAlbum = new Album();
        String nombreAlbum = txtNombreAlbum.getText();
        int anio = Integer.parseInt(txtAnioAlbum.getText());
        int id = Integer.parseInt(txtIDAlbumArtista.getText());

        int idAlbum = Integer.parseInt(txtIdAlbum.getText());

        if (id == 0) {
            nuevoAlbum.setId(idAlbum);
            nuevoAlbum.setNombre(nombreAlbum);
            nuevoAlbum.setAnio(anio);
            nuevoAlbum.setActualizadoEl(actualizadoEL);
            albumDAO.actualizarAlbumSiArtista(nuevoAlbum);
            Album.albums.clear();
            albumDAO.obtenerAlbum();
            Servicio.limpiarTabla(tblAlbums);
            mostrarDatosEnTabla(tblAlbums);
            JOptionPane.showMessageDialog(null, "Registro actualizado!");
            limpiarDatos();
        } else {
            nuevoAlbum.setNombre(nombreAlbum);
            nuevoAlbum.setAnio(anio);
            nuevoAlbum.setArtistaId(id);
            nuevoAlbum.setId(idAlbum);
            nuevoAlbum.setActualizadoEl(actualizadoEL);
            albumDAO.actualizarAlbumArtista(nuevoAlbum);
            Album.albums.clear();
            albumDAO.obtenerAlbum();
            Servicio.limpiarTabla(tblAlbums);
            mostrarDatosEnTabla(tblAlbums);
            JOptionPane.showMessageDialog(null, "Registro actualizado!");
            limpiarDatos();
        }


    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btnRespuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton rbRespuestaArtistaNo;
    private javax.swing.JRadioButton rbRespuestaArtistaSi;
    private javax.swing.JTable tblAlbums;
    private javax.swing.JTextField txtAnioAlbum;
    public javax.swing.JTextField txtIDAlbumArtista;
    private javax.swing.JTextField txtIdAlbum;
    public transient javax.swing.JTextField txtNombreAlbum;
    public javax.swing.JTextField txtNombreAlbumArtista;
    // End of variables declaration//GEN-END:variables
}
